version: "3.1"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672" # Porta padrão do RabbitMQ
            - "15672:15672" # Porta da interface de gerenciamento
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
